### ISSUE TITLE
Need to check code

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#29]
Today I came across this:

![image](https://user-images.githubusercontent.com/2317133/64584344-eb306400-d3b1-11e9-8a86-42e85e1757fa.png)

Now, the logic was that we fetch active contests, and **among these contest** we needed to determine if the user has submissions uploaded.

If ACTIVE CONTESTS section failed to load, how did ACTIVE SUBMISSIONS load - if one were to follow the above logic?

I need to go through the code here...

**Comment by callmekatootie** [comment]
Note: A refresh / reload did load the ACTIVE CONTESTS after the above was seen

**Comment by callmekatootie** [comment]
The error in console:

```
An error occured while requesting a v3 token: %j StatusCodeError: 500 - "{\"id\":\"-7b64e40d:16d078ecc45:2f92\",\"result\":{\"success\":true,\"status\":500,\"metadata\":null,\"content\":\"java.sql.SQLException: Could not do a physical-order read to fetch next row. [statement:\\\"SELECT u.user_id AS id, u.first_name AS firstName, u.last_name AS lastName, u.handle, u.create_date AS createdAt, u.modify_date AS modifiedAt, reg_source AS regSource, u.utm_source AS utmSource, u.utm_medium AS utmMedium, u.utm_campaign AS utmCampaign, u.status AS status, u.activation_code AS credential$activationCode, s.password AS credential$encodedPassword, e.address AS email, e.status_id AS emailStatus FROM user AS u LEFT OUTER JOIN email AS e ON u.user_id = e.user_id AND e.email_type_id = 1 AND e.primary_ind = 1 LEFT OUTER JOIN security_user AS s ON u.user_id = s.login_id WHERE u.user_id = :id\\\", located:\\\"SELECT u.user_id AS id, u.first_name AS firstName, u.last_name AS lastName, u.handle, u.create_date AS createdAt, u.modify_date AS modifiedAt, reg_source AS regSource, u.utm_source AS utmSource, u.utm_medium AS utmMedium, u.utm_campaign AS utmCampaign, u.status AS status, u.activation_code AS credential$activationCode, s.password AS credential$encodedPassword, e.address AS email, e.status_id AS emailStatus FROM user AS u LEFT OUTER JOIN email AS e ON u.user_id = e.user_id AND e.email_type_id = 1 AND e.primary_ind = 1 LEFT OUTER JOIN security_user AS s ON u.user_id = s.login_id WHERE u.user_id = :id\\\", rewritten:\\\"/* UserDAO.findUserById */ SELECT u.user_id AS id, u.first_name AS firstName, u.last_name AS lastName, u.handle, u.create_date AS createdAt, u.modify_date AS modifiedAt, reg_source AS regSource, u.utm_source AS utmSource, u.utm_medium AS utmMedium, u.utm_campaign AS utmCampaign, u.status AS status, u.activation_code AS credential$activationCode, s.password AS credential$encodedPassword, e.address AS email, e.status_id AS emailStatus FROM user AS u LEFT OUTER JOIN email AS e ON u.user_id = e.user_id AND e.email_type_id = 1 AND e.primary_ind = 1 LEFT OUTER JOIN security_user AS s ON u.user_id = s.login_id WHERE u.user_id = ?\\\", arguments:{ positional:{}, named:{id:23124329}, finder:[]}]\"},\"version\":\"v3\"}"
	at new StatusCodeError (/home/mithun/Desktop/projects/topcoder/ide-ext-vscode/node_modules/request-promise-core/lib/errors.js:32:15)
	at Request.module.exports.plumbing.callback (/home/mithun/Desktop/projects/topcoder/ide-ext-vscode/node_modules/request-promise-core/lib/plumbing.js:104:33)
	at Request.RP$callback [as _callback] (/home/mithun/Desktop/projects/topcoder/ide-ext-vscode/node_modules/request-promise-core/lib/plumbing.js:46:31)
	at Request.init.self.callback (/home/mithun/Desktop/projects/topcoder/ide-ext-vscode/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (/home/mithun/Desktop/projects/topcoder/ide-ext-vscode/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (/home/mithun/Desktop/projects/topcoder/ide-ext-vscode/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1092:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by cwdcwd** [comment]
that looks like an error thrown from the v3/v4 challenges API
