### ISSUE TITLE
1 Test fails

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/ide-ext-vscode#34]
Issue reported by reviewer Mayur.Joshi

1 test fails

  1) ChallengeService Unit tests
```
       uploadSubmmission() success should return success response:

     Error: Failed to submit the workspace to the challenge.

  	at Function.<anonymous> (out/services/ChallengeService.js:216:23)

  	at Generator.throw (<anonymous>)

  	at rejected (out/services/ChallengeService.js:5:65)
```

**Comment by callmekatootie** [comment]
Cannot reproduce. Closing.
